const ScoreTrackerTypes = {
    SET__SCORE_TRACKER_PLAYER_NAMES: 'SET__SCORE_TRACKER_PLAYER_NAMES',
    SET__SCORE_TRACKER_PLAYER_SCORE: 'SET__SCORE_TRACKER_PLAYER_SCORE',

    SAVE__SCORE_TRACKER_CURRENT_GAME: 'SAVE__SCORE_TRACKER_CURRENT_GAME',

    RESET__SCORE_TRACKER_PLAYER_DATA: 'RESET__SCORE_TRACKER_PLAYER_DATA',

    RESET__SCORE_TRACKER_PLAYER_SCORES: 'RESET__SCORE_TRACKER_PLAYER_SCORES'
}

export default ScoreTrackerTypes;
