
const AuthTypes = {
    RUN__AUTH__USER_LOGOUT: 'RUN__AUTH__USER_LOGOUT',
    TOGGLE__AUTH__LOGIN_REQUIRED_MODAL: 'TOGGLE__AUTH__LOGIN_REQUIRED_MODAL',

    SET__AUTH__IS_USER_LOGGED_IN: 'SET__AUTH__IS_USER_LOGGED_IN',

    SAVE__AUTH__USER_LOGIN: 'SAVE__AUTH__USER_LOGIN',
    SAVE__AUTH__USER_LOGIN__STATUS: 'SAVE__AUTH__USER_LOGIN__STATUS',
    SAVE__AUTH__USER_LOGIN__LOADING: 'SAVE__AUTH__USER_LOGIN__LOADING',
    SAVE__AUTH__USER_LOGIN__SUCCESS: 'SAVE__AUTH__USER_LOGIN__SUCCESS',
    SAVE__AUTH__USER_LOGIN__ERROR: 'SAVE__AUTH__USER_LOGIN__ERROR',


    SET__AUTH__USER_SIGNUP: 'SET__AUTH__USER_SIGNUP',

    SAVE__AUTH__USER_SIGNUP: 'SAVE__AUTH__USER_SIGNUP',
    SAVE__AUTH__USER_SIGNUP__STATUS: 'SAVE__AUTH__USER_SIGNUP__STATUS',
    SAVE__AUTH__USER_SIGNUP__LOADING: 'SAVE__AUTH__USER_SIGNUP__LOADING',
    SAVE__AUTH__USER_SIGNUP__SUCCESS: 'SAVE__AUTH__USER_SIGNUP__SUCCESS',
    SAVE__AUTH__USER_SIGNUP__ERROR: 'SAVE__AUTH__USER_SIGNUP__ERROR',

    CHECK__AUTH__USER_LOGIN: 'CHECK__AUTH__USER_LOGIN',
    CHECK__AUTH__USER_LOGIN__STATUS: 'CHECK__AUTH__USER_LOGIN__STATUS',
    CHECK__AUTH__USER_LOGIN__LOADING: 'CHECK__AUTH__USER_LOGIN__LOADING',
    CHECK__AUTH__USER_LOGIN__SUCCESS: 'CHECK__AUTH__USER_LOGIN__SUCCESS',
    CHECK__AUTH__USER_LOGIN__ERROR: 'CHECK__AUTH__USER_LOGIN__ERROR',


    SET__AUTH__USER_LOGOUT: 'SET__AUTH__USER_LOGOUT',

    SAVE__AUTH__USER_LOGOUT: 'SAVE__AUTH__USER_LOGOUT',
    SAVE__AUTH__USER_LOGOUT__STATUS: 'SAVE__AUTH__USER_LOGOUT__STATUS',
    SAVE__AUTH__USER_LOGOUT__LOADING: 'SAVE__AUTH__USER_LOGOUT__LOADING',
    SAVE__AUTH__USER_LOGOUT__SUCCESS: 'SAVE__AUTH__USER_LOGOUT__SUCCESS',
    SAVE__AUTH__USER_LOGOUT__ERROR: 'SAVE__AUTH__USER_LOGOUT__ERROR',

    SAVE__ADMIT__FORM: 'SAVE__ADMIT__FORM',
    GET__ADMIT__FORM: 'GET__ADMIT__FORM',
    SET__ADMITTED_PATIENTS: 'SET__ADMITTED_PATIENTS',
    SAVE__PAYMENT_DETAILS_FOR_ADMISSION_NUMBER: 'SAVE__PAYMENT_DETAILS_FOR_ADMISSION_NUMBER',
    GET__PAYMENT_DETAILS_FOR_ADMISSION_NUMBER: 'GET__PAYMENT_DETAILS_FOR_ADMISSION_NUMBER',
    SET__PAYMENT_DETAILS_FOR_ADMISSION_NUMBER: 'SET__PAYMENT_DETAILS_FOR_ADMISSION_NUMBER',

    SET_GET__PAYMENT_DETAILS_FOR_ADMISSION_NUMBER__CALL_STATUS: 'SET_GET__PAYMENT_DETAILS_FOR_ADMISSION_NUMBER__CALL_STATUS',

    SET__EDIT_MODE_FOR_ADMIT_FORM: 'SET__EDIT_MODE_FOR_ADMIT_FORM',



    SAVE__INTEREST__FORM: 'SAVE__INTEREST__FORM',
    GET__INTEREST__FORM: 'GET__INTEREST__FORM',
    SET__INTEREST_FILLED_PATIENTS: 'SET__INTEREST_FILLED_PATIENTS',

    SAVE__INVOICE__DETAILS: 'SAVE__INVOICE__DETAILS',
    GET__INVOICE__DETAILS: 'GET__INVOICE__DETAILS',
    GET__INVOICE__DETAILS__STATUS: 'GET__INVOICE__DETAILS__STATUS',
    SET__INVOICE__DETAILS: 'SET__INVOICE__DETAILS',


};
export default AuthTypes;
